# Generated by Django 5.0.1 on 2024-01-31 05:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("new_agency", models.CharField(max_length=50)),
                ("link", models.URLField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Articles",
                "ordering": ["-title"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Transportation Design", "TD"),
                            ("Industrial Design", "ID"),
                            ("Retail Space Design", "RSD"),
                            ("Packaging Design", "PD"),
                            ("Branding and Identity Design", "BID"),
                            ("UI UX Design", "UD"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("client", models.CharField(blank=True, max_length=50)),
                ("service", models.CharField(blank=True, max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("duration", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("context", models.TextField(blank=True)),
                ("approach", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Projects",
                "ordering": ["-date"],
            },
        ),
    ]
