# Generated by Django 5.0.1 on 2024-02-04 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="new_agency",
            new_name="news_agency",
        ),
    ]
