# Generated by Django 5.0.2 on 2024-02-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_new_agency_article_news_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="long_image1",
            field=models.ImageField(default="ABCBC.com", upload_to="projects/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="long_image2",
            field=models.ImageField(null=True, upload_to="projects/"),
        ),
        migrations.AddField(
            model_name="project",
            name="short_image1",
            field=models.ImageField(null=True, upload_to="projects/"),
        ),
        migrations.AddField(
            model_name="project",
            name="short_image2",
            field=models.ImageField(null=True, upload_to="projects/"),
        ),
    ]
