# Generated by Django 5.0.2 on 2024-02-18 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_project_long_image1_project_long_image2_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Articles"},
        ),
        migrations.AddField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 2, 18, 16, 25, 19, 500176, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
