# Generated by Django 5.0.3 on 2024-03-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_long_image2_project_cover_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="country",
            field=models.CharField(default="India", editable=False, max_length=50),
        ),
    ]
