# Generated by Django 5.0.3 on 2024-03-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_project_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="link",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="news_agency",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="project",
            name="approach",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("Transportation Design", "TD"),
                    ("Industrial Design", "ID"),
                    ("Retail Space Design", "RSD"),
                    ("Packaging Design", "PD"),
                    ("Branding and Identity Design", "BID"),
                    ("UI UX Design", "UD"),
                ],
                max_length=400,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name="project",
            name="country",
            field=models.CharField(default="India", editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="duration",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="project",
            name="service",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=400),
        ),
    ]
