# Generated by Django 5.0.3 on 2024-03-30 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_article_link_alter_article_news_agency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="clients/")),
            ],
            options={
                "verbose_name_plural": "Clients",
                "ordering": ["id"],
            },
        ),
    ]
