# Generated by Django 5.0.3 on 2024-03-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_client_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="title",
            field=models.CharField(default="Client", editable=False, max_length=400),
        ),
    ]
